# **Autovalori**

In [ ]:
import numpy as np

La funzione numpy.linalg.eig(A) restituisce una coppia di autovelori e autovettori di A. <br>
Il vettore w contiene gli autovalori. La matrice v contiene i corrispondenti autovettori, uno per colonna. <br>

In [ ]:
A = np.array([  [1, 2, 3],
                [3, 2, 1], 
                [1, 0, -1]])

w, v = np.linalg.eig(A)
print(w)
print(v)

[ 4.31662479e+00 -2.31662479e+00  1.93041509e-17]
[[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]


Possiamo controllare che un autovalore in w e il rispettivo autovettore rispettano la condizione 𝐴𝑥= λ𝑥

In [ ]:
u = v[:,1] # Estrazione del secondo autovettore
print(u)
print(np.linalg.norm(u, ord=2)) # Controllo della norma

lam = w[1] # Estrazione del secondo autovalore
print(lam)

print(np.dot(A,u))	# Calcolo e stampa di 𝐴𝑥
print(lam*u)	    # Calcolo e stampa di 𝜆𝑥

[ 0.73595785 -0.38198836 -0.55897311]
1.0
-2.3166247903554
[-1.7049382   0.88492371  1.29493096]
[-1.7049382   0.88492371  1.29493096]


Gli autovalori restituiti non sono ordinati!<br>
È spesso utile ordinare gli autovalori in ordine discendente, e riordinare gli autovettori per farli ancora corrispondere.<br>
Usiamo un ordinamento “indiretto” tramite la funzione argsort. Un ordinamento indiretto restituisce una lista di indici, da applicare successimanete ai vettori w e v.


In [ ]:
# Ordinamento degli autovalori
w, v = np.linalg.eig(A)
idx = np.argsort(w)
w = w[idx]
v = v[:,idx]
print(w)
print(v)

[-2.31662479e+00  1.93041509e-17  4.31662479e+00]
[[ 0.73595785  0.40824829  0.58428153]
 [-0.38198836 -0.81649658  0.80407569]
 [-0.55897311  0.40824829  0.10989708]]




---

