In [49]:
import numpy as np

np.set_printoptions(precision=15)

# **Jacobi**

In [50]:
def jacobi(A: np.array, b: np.array, x0: np.array, toll: float, n_max: int, verbose=False):
    """
    Risoluzione di un sistema lineare Ax=b data un'approssimazione iniziale x0.
    L'algoritmo implementa il metodo iterativo di Jacobi.

    :param A: matrice dei coefficienti
    :param b: vettore colonna dei termini noti
    :param x0: approssimazione iniziale
    :param toll: tolleranza, ovvero precisione relativa richiesta
    :param n_max: massimo numero di iterazioni
    :param verbose: se True, stampa informazioni sulle iterazioni
    :return: soluzione x, stima dell'errore, numero di iterazioni eseguite 
    :rtype: np.array, float, int
    """

    # Inizializzazioni
    rows = np.size(A, 0)
    cols = np.size(A, 1)
    n_iter = 0
    stima_errore = 1.0
    x = np.copy(x0)

    # Processo iterativo
    while n_iter < n_max and stima_errore >= toll:

        for i in range(rows):

            somma1 = 0
            for j in range(i):
                somma1 += A[i, j] * x0[j]

            somma2 = 0
            for j in range(i+1, cols):
                somma2 += A[i, j] * x0[j]

            x[i] = (b[i] - somma1 - somma2) / A[i, i]

        if verbose:
            print("valore di x alla iterazione numero ",
                  n_iter, ", stima errore =", stima_errore)
            print(x.T)

        stima_errore = np.linalg.norm(x-x0, np.inf) / np.linalg.norm(x, np.inf)
        n_iter += 1
        x0 = np.copy(x)

    return x, stima_errore, n_iter

In [51]:
def jacobi_decomposizione(A, b, x0, toll, n_max, verbose=False):
    """
    Risoluzione di un sistema lineare Ax=b data un'approssimazione iniziale x0.
    L'algoritmo implementa il metodo iterativo di Jacobi usando la decomposizione 
    della matrice dei coefficienti A = D + C.

    :param A: matrice dei coefficienti
    :param b: vettore colonna dei termini noti
    :param x0: approssimazione iniziale
    :param toll: tolleranza, ovvero precisione relativa richiesta
    :param n_max: massimo numero di iterazioni
    :param verbose: se True, stampa informazioni sulle iterazioni
    :return: soluzione x, stima dell'errore, numero di iterazioni eseguite
    :rtype: np.array, float, int
    """

    # calcolo matrici D e C
    D = np.diag(np.diag(A))
    C = A - D

    # Inizializzazioni
    n_iter = 0
    x = np.copy(x0)

    # Processo iterativo
    while n_iter < n_max:
        x = np.dot(np.linalg.inv(D), (b - np.dot(C, x0)))

        stima_errore = np.linalg.norm(x-x0, np.inf) / np.linalg.norm(x, np.inf)
        if stima_errore <= toll:
            break
        x0 = np.copy(x)
        n_iter += 1
        if verbose:
            print("valore di x alla iterazione numero ",
                  n_iter, ", stima errore =", stima_errore)
            print(x.T)

    return x, stima_errore, n_iter

In [52]:
def jacobi_decomposizione_ottimizzato(A, b, x0, toll, n_max, verbose=False):
    """
    Risoluzione di un sistema lineare Ax=b data un'approssimazione iniziale x0.
    L'algoritmo implementa il metodo iterativo di Jacobi usando la decomposizione 
    della matrice dei coefficienti A = D + C.

    :param A: matrice dei coefficienti
    :param b: vettore colonna dei termini noti
    :param x0: approssimazione iniziale
    :param toll: tolleranza, ovvero precisione relativa richiesta
    :param n_max: massimo numero di iterazioni
    :param verbose: se True, stampa informazioni sulle iterazioni
    :return: soluzione x, stima dell'errore, numero di iterazioni eseguite
    :rtype: np.array, float, int
    """

    # calcolo matrici D e C
    D = np.diag(np.diag(A))
    C = A - D

    # Inizializzazioni
    n_iter = 0
    x = np.copy(x0)

    # Matrici iterative
    B = np.dot(np.linalg.inv(D), b)
    c = np.dot(np.linalg.inv(D), C)

    # Processo iterativo
    while n_iter < n_max:
        x = B - np.dot(c, x0)

        stima_errore = np.linalg.norm(x-x0, np.inf) / np.linalg.norm(x, np.inf)
        if stima_errore <= toll:
            break
        x0 = np.copy(x)
        n_iter += 1
        if verbose:
            print("valore di x alla iterazione numero ",
                  n_iter, ", stima errore =", stima_errore)
            print(x.T)

    return x, stima_errore, n_iter

# **Gauss Seidel**

In [53]:
def gauss_seidel(A: np.array, b: np.array, x0: np.array, toll: float, n_max: int, verbose=False):
    """
    Risoluzione di un sistema lineare Ax=b data un'approssimazione iniziale x0.
    L'algoritmo implementa il metodo iterativo di Gauss Seidel.

    :param A: matrice dei coefficienti
    :param b: vettore colonna dei termini noti
    :param x0: approssimazione iniziale
    :param toll: tolleranza, ovvero precisione relativa richiesta
    :param n_max: massimo numero di iterazioni
    :param verbose: se True, stampa informazioni sulle iterazioni
    :return: soluzione x, stima dell'errore, numero di iterazioni eseguite
    :rtype: np.array, float, int
    """

    # Inizializzazioni
    rows = np.size(A, 0)
    n_iter = 0
    stima_errore = 1.0
    x = np.copy(x0)

    # Processo iterativo
    while n_iter < n_max and stima_errore >= toll:

        for i in range(0, rows):

            somma1 = 0
            for j in range(i):
                somma1 = somma1 + A[i, j] * x[j]

            somma2 = 0
            for j in range(i+1, rows):
                somma2 = somma2 + A[i, j] * x0[j]

            x[i] = (b[i] - somma1 - somma2) / A[i, i]

        if verbose:
            print("valore di x alla iterazione numero ", n_iter)
            print(x.T)

        stima_errore = np.linalg.norm(x-x0, np.inf) / np.linalg.norm(x, np.inf)
        n_iter += 1
        x0 = np.copy(x)

    return x, stima_errore, n_iter




In [54]:
def gauss_seidel_decomposizione(A, b, x0, toll, iter_max, verbose=False):
    """
    Risoluzione di un sistema lineare Ax=b data un'approssimazione iniziale x0.
    L'algoritmo implementa il metodo iterativo di Gauss Seidel usando la decomposizione 
    della matrice dei coefficienti A = L + U.

    :param A: matrice dei coefficienti
    :param b: vettore colonna dei termini noti
    :param x0: approssimazione iniziale
    :param toll: tolleranza, ovvero precisione relativa richiesta
    :param n_max: massimo numero di iterazioni
    :param verbose: se True, stampa informazioni sulle iterazioni
    :return: soluzione x, stima dell'errore, numero di iterazioni eseguite
    :rtype: np.array, float, int
    """

    # calcolo matrici L=lower e U=upper
    lower = np.tril(A)
    upper = A - lower

    # Inizializzazioni
    n_iter = 0
    x = np.copy(x0)

    # Processo iterativo
    while n_iter < iter_max:
        x = np.dot(np.linalg.inv(lower), (b - np.dot(upper, x0)))
        n_iter += 1
        stima_errore = np.linalg.norm(x-x0, np.inf) / np.linalg.norm(x, np.inf)
        if stima_errore <= toll:
            break
        x0 = np.copy(x)

    return x, stima_errore, n_iter


In [55]:
def gauss_seidel_decomposizione_ottimizzato(A, b, x0, toll, iter_max, verbose=False):
    """
    Risoluzione di un sistema lineare Ax=b data un'approssimazione iniziale x0.
    L'algoritmo implementa il metodo iterativo di Gauss Seidel usando la decomposizione 
    della matrice dei coefficienti A = L + U.

    :param A: matrice dei coefficienti
    :param b: vettore colonna dei termini noti
    :param x0: approssimazione iniziale
    :param toll: tolleranza, ovvero precisione relativa richiesta
    :param n_max: massimo numero di iterazioni
    :param verbose: se True, stampa informazioni sulle iterazioni
    :return: soluzione x, stima dell'errore, numero di iterazioni eseguite
    :rtype: np.array, float, int
    """

    # calcolo matrici L=lower e U=upper
    lower = np.tril(A)
    upper = A - lower

    # Inizializzazioni
    n_iter = 0
    x = np.copy(x0)

    # Matrici iterative
    B = np.dot(np.linalg.inv(lower), b)
    c = np.dot(np.linalg.inv(lower), upper)

    # Processo iterativo
    while n_iter < iter_max:
        x = B - np.dot(c, x0)
        n_iter += 1
        stima_errore = np.linalg.norm(x-x0, np.inf) / np.linalg.norm(x, np.inf)
        if stima_errore <= toll:
            break
        x0 = np.copy(x)

    return x, stima_errore, n_iter


# **Script**

In [57]:
A = np.array([  [15, -6, 1, 2],
                [1, 10, -2, 5],
                [-4, 1, 10, -3],
                [-5, -2, -1, 10]],
                dtype=float)
b = np.array([[9],
              [37],
              [43],
              [3]],
             dtype=float)
print("Matrice completa del sistema:")
print(np.append(A, b, 1))
print("Indice di condizionamento:", np.linalg.cond(A))

xVero = np.array([[2],
                  [4],
                  [5],
                  [1]],
                 dtype=float)
print("Soluzione carta e penna:")
print(xVero)

xNumpy = np.linalg.solve(A, b)
print("Soluzione numpy.linalg.solve:")
print(xNumpy)

x0 = np.zeros((np.size(b, 0),1))
toll = 1e-15
nMax = 100


Matrice completa del sistema:
[[15. -6.  1.  2.  9.]
 [ 1. 10. -2.  5. 37.]
 [-4.  1. 10. -3. 43.]
 [-5. -2. -1. 10.  3.]]
Indice di condizionamento: 2.124514450078569
Soluzione carta e penna:
[[2.]
 [4.]
 [5.]
 [1.]]
Soluzione numpy.linalg.solve:
[[1.362273901808785]
 [3.496640826873385]
 [5.154005167958656]
 [2.195865633074936]]


In [58]:
print("\nSoluzione con metodo di Jacobi")
xJacobi, stimaErrore, nIter = jacobi(A, b, x0, toll, nMax)
print(xJacobi)
print("nIter Jacobi:", nIter)

errRel = np.linalg.norm(xJacobi-xVero, np.inf) / \
        np.linalg.norm(xVero, np.inf)
print("errore relativo Jacobi:", errRel)


Soluzione con metodo di Jacobi
[[1.362273901808787]
 [3.496640826873386]
 [5.154005167958654]
 [2.195865633074935]]
nIter Jacobi: 54
errore relativo Jacobi: 0.23917312661498702


In [59]:
print("\nSoluzione con metodo di Jacobi con decomposizione")
xJacobi, stimaErrore, nIter = jacobi_decomposizione(A, b, x0, toll, nMax)
print(xJacobi)
print("stimaErrore Jacobi:", stimaErrore)
print("nIter Jacobi:", nIter)

errRel = np.linalg.norm(xJacobi-xVero, np.inf) / \
        np.linalg.norm(xVero, np.inf)
print("errore relativo Jacobi:", errRel)


Soluzione con metodo di Jacobi con decomposizione
[[1.362273901808787]
 [3.496640826873387]
 [5.154005167958655]
 [2.195865633074935]]
stimaErrore Jacobi: 6.893112371883056e-16
nIter Jacobi: 53
errore relativo Jacobi: 0.23917312661498702


In [60]:
print("\nSoluzione con metodo di Jacobi con decomposizione e ottimizzazione")
xJacobiDEC_OPT, stimaErroreDEC_OPT, nIterDEC_OPT = jacobi_decomposizione_ottimizzato(A, b, x0, toll, nMax)
print(xJacobiDEC_OPT) 
print("stimaErrore Jacobi:", stimaErroreDEC_OPT)
print("nIter Jacobi:", nIterDEC_OPT)

errRel = np.linalg.norm(xJacobiDEC_OPT-xVero, np.inf) / \
        np.linalg.norm(xVero, np.inf)
print("errore relativo Jacobi:", errRel)


Soluzione con metodo di Jacobi con decomposizione e ottimizzazione
[[1.362273901808787]
 [3.496640826873386]
 [5.154005167958655]
 [2.195865633074935]]
stimaErrore Jacobi: 6.893112371883056e-16
nIter Jacobi: 53
errore relativo Jacobi: 0.23917312661498702


In [61]:
print("\nSoluzione con metodo di Gauss-Seidel")
xGaussSeidel, stimaErrore, nIter = gauss_seidel(A, b, x0, toll, nMax)
print(xGaussSeidel)
print("stimaErrore GaussSeidel:", stimaErrore)
print("nIter GaussSeidel:", nIter)

errRel = np.linalg.norm(xGaussSeidel-xVero, np.inf) / \
        np.linalg.norm(xVero, np.inf)
print("errore relativo GaussSeidel:", errRel)


Soluzione con metodo di Gauss-Seidel
[[1.362273901808786]
 [3.496640826873384]
 [5.154005167958656]
 [2.195865633074936]]
stimaErrore GaussSeidel: 3.4465561859415265e-16
nIter GaussSeidel: 33
errore relativo GaussSeidel: 0.2391731266149871


In [62]:
print("\nSoluzione con metodo di Gauss-Seidel con decomposizione")
xGaussSeidelDEC, stimaErroreDEC, nIterDEC = gauss_seidel_decomposizione(A, b, x0, toll, nMax)
print(xGaussSeidelDEC) 
print("stimaErrore GaussSeidel:", stimaErroreDEC)
print("nIter GaussSeidel:", nIterDEC)

errRelDEC = np.linalg.norm(xGaussSeidelDEC-xVero, np.inf) / \
        np.linalg.norm(xVero, np.inf)
print("errore relativo GaussSeidel:", errRelDEC)


Soluzione con metodo di Gauss-Seidel con decomposizione
[[1.362273901808786]
 [3.496640826873385]
 [5.154005167958656]
 [2.195865633074936]]
stimaErrore GaussSeidel: 1.7232780929707633e-16
nIter GaussSeidel: 33
errore relativo GaussSeidel: 0.23917312661498719


In [63]:
print("\nSoluzione con metodo di Gauss-Seidel con decomposizione e ottimizzazione")
xGaussSeidelDEC_OPT, stimaErroreDEC_OPT, nIterDEC_OPT = gauss_seidel_decomposizione_ottimizzato(A, b, x0, toll, nMax)
print(xGaussSeidelDEC) 
print("stimaErrore GaussSeidel:", stimaErroreDEC_OPT)
print("nIter GaussSeidel:", nIterDEC_OPT)

errRelDEC_OPT = np.linalg.norm(xGaussSeidelDEC_OPT-xVero, np.inf) / \
        np.linalg.norm(xVero, np.inf)
print("errore relativo GaussSeidel:", errRelDEC_OPT)


Soluzione con metodo di Gauss-Seidel con decomposizione e ottimizzazione
[[1.362273901808786]
 [3.496640826873385]
 [5.154005167958656]
 [2.195865633074936]]
stimaErrore GaussSeidel: 3.4465561859415265e-16
nIter GaussSeidel: 33
errore relativo GaussSeidel: 0.2391731266149871


In [64]:
xNumpy = np.linalg.solve(A, b)
print("Soluzione numpy.linalg.solve:")
print(xNumpy)

Soluzione numpy.linalg.solve:
[[1.362273901808785]
 [3.496640826873385]
 [5.154005167958656]
 [2.195865633074936]]
